version: "3.8"
   
services:
    django:
        build: 
          context: .
          dockerfile: Dockerfile.prod
        container_name: django
        command: gunicorn djcera.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        env_file:
            - ./.env.prod
        environment:
            - CELERY_BROKER=redis://redis:6379/0
        depends_on:
            - db
            - redis
    celery:
        build: .
        command: celery -A djcera worker -l INFO
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
        depends_on:
            - django
            - redis 
    redis:
        image: "redis:alpine"

    db:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ./.env.prod.db

    nginx:
      build: ./nginx
      ports:
        - 1337:80
      depends_on:
        - django

volumes:
  postgres_data: